# Generated by Django 5.2.4 on 2025-07-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeiro',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='especialidade',
        ),
    ]
