# Generated by Django 5.2.4 on 2025-07-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rede_hospitalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('enfermaria', 'Enfermaria'), ('uti', 'UTI')], max_length=50)),
                ('ocupado', models.BooleanField(default=False)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_hospitalar.unidade_hospitalar')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receitas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_hospitalar.unidade_hospitalar')),
            ],
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_hospitalar.unidade_hospitalar')),
            ],
        ),
    ]
