# Generated by Django 5.2.4 on 2025-07-07 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissionais', '0002_remove_enfermeiro_especialidade_and_more'),
        ('rede_hospitalar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='tipo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profissionais.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='resumo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rede_hospitalar.unidade_hospitalar'),
        ),
        migrations.AddField(
            model_name='exame',
            name='resumo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rede_hospitalar.unidade_hospitalar'),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('historico', models.TextField()),
                ('consultas', models.ManyToManyField(blank=True, related_name='prontuarios', to='pacientes.consulta')),
                ('exames', models.ManyToManyField(blank=True, related_name='prontuarios', to='pacientes.exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
