# Generated by Django 5.2.4 on 2025-07-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_remove_consulta_motivo_remove_exame_resultado_and_more'),
        ('profissionais', '0004_prescricao_data_prescricao_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('chat', 'Chat')], max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PrescricaoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('medicamento', models.CharField(max_length=100)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profissionais.medico')),
            ],
        ),
    ]
